/**
 * Name: Rusho Binnabi
 * Date: 7/21/2023
 * Project: Unifier App - Number Generator Function
 * Contact Information: RushoBinnabi123@yahoo.com
 * Code File Updated: 7/21/2023 at 11:23 PM
 */

package rusho.app.unifer;

import android.content.Intent;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;

import java.util.Random;

/**
 * this NumberGenerator class has all the things needed for the Number Generator function of the app to run.
 */

public class NumberGenerator extends AppCompatActivity {

    // this class generates a random number between a range of two numbers entered by the user.

    Button clearNumberButton;
    Button generateNumberButton;
    String number1text;
    String number2text;
    int number1;
    int number2;
    int randomNumber;
    EditText enterNumber1;
    EditText enterNumber2;
    Random numberGenerator;

    /**
     * this protected onCreate() method, which uses the Bundle savedInstanceObject as its argument, 
     * has the code for the Number Generator function that the Unifier app needs to function.
     * @param savedInstanceState the argument is the bundle object that makes it so the app starts off where it last left off.
     */

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_number_generator);
        activate();
        clearNumberButton.setOnClickListener(v -> clearNumber());
        generateNumberButton.setOnClickListener(v -> generateNumber());
    }

    /**
     * this public void numberGeneratorChangetoMainMenuScreen() method changes the screen to main menu screen of the app.
     * @param view the view is the screen of the app being changed.
     */

    public void numberGeneratorChangetoMainMenuScreen(View view) {
        Intent intent = new Intent(view.getContext(), MainActivity.class);
        startActivity(intent);
    }

    /**
     * this private void generateNumber() method generates a random number between a range of two numbers entered by the user.
     */

    private void generateNumber() {
        try {
            number1text = enterNumber1.getText().toString();
            number2text = enterNumber2.getText().toString();
            number1 = Integer.parseInt(number1text);
            number2 = Integer.parseInt(number2text);
            randomNumber = numberGenerator.nextInt((number2 - number1) + 1) + number1; // randomNumber will have the number that is generated by the range of two numbers within number1 and number2.
            showRandomNumber();
        }
        catch (NumberFormatException n) {
            Toast toast = Toast.makeText(this, "Error. Please enter two numbers", Toast.LENGTH_SHORT);
            toast.setGravity(Gravity.BOTTOM, 0, 120);
            toast.show();
        }
    }

    /**
     * this private void showRandomNumber() method shows the randomly generated number that is between a range of two numbers.
     */

    private void showRandomNumber() {
        Toast toast = Toast.makeText(this, "Randomly generated number between " + number1 + " and " + number2 + ": " + randomNumber, Toast.LENGTH_SHORT);
        toast.setGravity(Gravity.BOTTOM, 0, 120);
        toast.show();
    }

    /**
     * this private void clearNumber() method clears all the data from all the variables and objects.
     */

    private void clearNumber() {
        number1text = "";
        number2text = "";
        number1 = 0;
        number2 = 0;
        randomNumber = 0;
        enterNumber1.getText().clear();
        enterNumber2.getText().clear();
    }

    /**
     * this private void activate() method initializes all the variables and objects.
     */

    private void activate() {
        clearNumberButton = findViewById(R.id.ClearNumberButton);
        generateNumberButton = findViewById(R.id.GenerateNumberButton);
        numberGenerator = new Random();
        number1text = "";
        number2text = "";
        number1 = 0;
        number2 = 0;
        randomNumber = 0;
        enterNumber1 = findViewById(R.id.EnterNumber1);
        enterNumber2 = findViewById(R.id.EnterNumber2);
    }

}